/** Theme from docs/DESIGN.md — full Stitch token set. */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}', './src/stitch/*.html'],
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fc",
        "surface-dim": "#d8dadd",
        "surface-bright": "#f7f9fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f7",
        "surface-container": "#eceef1",
        "surface-container-high": "#e6e8eb",
        "surface-container-highest": "#e0e3e6",
        "on-surface": "#191c1e",
        "on-surface-variant": "#42474f",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f4",
        "outline": "#72777f",
        "outline-variant": "#c2c7d0",
        "surface-tint": "#35618d",
        "primary": "#00375e",
        "on-primary": "#ffffff",
        "primary-container": "#1f4e79",
        "on-primary-container": "#95bff1",
        "inverse-primary": "#a0cafc",
        "secondary": "#1f686a",
        "on-secondary": "#ffffff",
        "secondary-container": "#a8eced",
        "on-secondary-container": "#256c6f",
        "tertiary": "#4c2e00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6a4300",
        "on-tertiary-container": "#e9b268",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d1e4ff",
        "primary-fixed-dim": "#a0cafc",
        "on-primary-fixed": "#001d35",
        "on-primary-fixed-variant": "#184974",
        "secondary-fixed": "#abeef0",
        "secondary-fixed-dim": "#8fd2d4",
        "on-secondary-fixed": "#002021",
        "on-secondary-fixed-variant": "#004f51",
        "tertiary-fixed": "#ffddb5",
        "tertiary-fixed-dim": "#f5bc72",
        "on-tertiary-fixed": "#2a1800",
        "on-tertiary-fixed-variant": "#643f00",
        "background": "#f7f9fc",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e6",
        "status-ai": "#1F4E79",
        "status-approved": "#2D8A4E",
        "status-pending": "#D97706",
        "status-rejected": "#DC2626",
        "brand-accent": "#ED5500",
        "text-main": "#485867",
        "primary-dark": "#00375e"
      },
      fontFamily: {
        display: ['"Hanken Grotesk"', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
